### ISSUE TITLE
This repository seems to be outdated and not working

### ISSUE THREAD

**Issue by rvalitov** [mailslurp/swagger-sdk-php#2]
Hello!
Thank you for your work.
Unfortunately, this repository is not mentioned in the official documentation. And it does not work (see #1)
The working repository is https://github.com/mailslurp/mailslurp-client-php
Perhaps, this repository should be deleted in order to avoid confusion and disappointment from the users?

**Comment by jackmahoney** [comment]
Yes sorry this repo needs to be deleted. thanks for pointing it out I will archive now
